spring:
  application:
    name: BE

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  devtools:
    restart:
      poll-interval: 1s

  env:
    jwt_secret: ${JWT_SECRET}
